apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariochart.fullname" . }}
  labels:
    {{- include "mariochart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 30245
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mariochart.selectorLabels" . | nindent 4 }}
